# Generated by Django 2.2.3 on 2020-09-10 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='商品ID(10桁)')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリ')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格(円)')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
